export default [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 14.98,
    img: "https://thumbs.dreamstime.com/z/healthy-breakfast-homemade-classic-american-pancakes-maple-syrup-served-fingerfood-sticks-stack-small-bamboo-brochettes-180275497.jpg",
    desc: `I'm baby woke milkshake wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "Quarentine buddy",
    category: "lunch",
    price: 9.98,
    img: "https://c8.alamy.com/comp/2BJ8G61/traditional-american-lunch-top-view-2BJ8G61.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral`,
  },
  {
    id: 3,
    title: "American classic",
    category: "breakfast",
    price: 12.58,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQntgwPT_zU6GItLWC1e1ZfphO1YMTIjrEGqQ&usqp=CAU",
    desc: `I'm baby woke milkshake wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 4,
    title: "buttermilk pancakes",
    category: "lunch",
    price: 8.98,
    img: "https://www.food-management.com/sites/food-management.com/files/Yakisoba_with_Chicken_and_Vegetables_0.jpg",
    desc: `I'm baby wolkencklnn jcvjfcv  fcxvhofdhc`,
  },
  {
    id: 5,
    title: "Dinner Double",
    category: "lunch",
    price: 10.98,
    img: "https://c8.alamy.com/comp/2BJ8G61/traditional-american-lunch-top-view-2BJ8G61.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
  },
  {
    id: 6,
    title: "Godzilla milshakes",
    category: "shakes",
    price: 7.98,
    img: "https://eatmodeon.com/wp-content/uploads/2019/10/WhatsApp-Image-2020-09-17-at-1.09.03-PM.jpeg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral`,
  },
  {
    id: 7,
    title: "Egg attack",
    category: "lunch",
    price: 18.98,
    img: "https://foodfornet.com/wp-content/uploads/2015/06/shutterstock_204677410.jpg",
    desc: `I'm baby wolkencklnn jcvjfcv  fcxvhofdhc`,
  },
  {
    id: 8,
    title: "country Delight",
    category: "Breakfast",
    price: 11.48,
    img: "https://media-cdn.tripadvisor.com/media/photo-s/05/d3/6a/89/american-classic-breakfast.jpg",
    desc: `I'm baby wolkencklnn jcvjfcv  fcxvhofdhc`,
  },
  {
    id: 9,
    title: "oreo dream",
    category: "shakes",
    price: 15.18,
    img: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8b3JlbyUyMHNoYWtlfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday `,
  },
  {
    id: 10,
    title: "oreo dream",
    category: "shakes",
    price: 15.18,
    img: "https://images.creativemarket.com/0.1.0/ps/2065204/300/200/m2/fpc/wm0/se9opkdrmluz1lwxqkidwwqrdvxqxtn7djpvu0ankruejhnxknjjelj4vbmh4mzp-.jpg?1482703759&s=5fd28613f459b652b01356a40fe9aed4",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
];
